name: Build and Deploy to ASC Site

on:
    workflow_call:
    push:
        branches:
            - main
            
jobs:
    build_site:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
            
          - name: Setup Ruby
            uses: ruby/setup-ruby@v1
            with:
              ruby-version: '3.4'
              bundler-cache: true
              
          - name: Install Jekyll
            run: |
                gem install jekyll
                
          - name: Build Site
            run: |
              jekyll build 
            
          - name: Upload Site Artifact
            uses: actions/upload-artifact@v4
            with:
              name: jekyll-site-build
              path: _site/
              
    upload_to_asc:
        needs: build_site
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo # for deploy script
            uses: actions/checkout@v4
            
          - name: Download Artifact
            uses: actions/download-artifact@v4
            with: 
                name: jekyll-site-build
                path: _site/
                
          - name: Setup Python
            uses: actions/setup-python@v5
            with: 
                python-version: '3.x'
                cache: 'pip'

          - run: pip install -r requirements.txt

          - name: Upload
            run: python ./upload_jekyll_site.py
            env:
              WP_URL: "https://www.americansolarchallenge.org"
              WP_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
              WP_APPLICATION_PASSWORD: ${{ secrets.WORDPRESS_APPLICATION_PASSWORD }}
              WP_PAGE_ID: ${{ secrets.WORDPRESS_PAGE_ID }}
              JEKYLL_HTML_PATH: _site/index.html 
              TARGET_DIV_ID: jekyll-site-wrapper
              ACF_FIELD_NAME: page_content_html 
            